name: tiny_expr
version: 0.3.0
description: A Dart library for evaluating mathematical expressions with support for variables and functions.
repository: https://github.com/shivanuj13/tiny_expr
homepage: https://github.com/shivanuj13/tiny_expr
issue_tracker: https://github.com/shivanuj13/tiny_expr/issues

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
